from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deleteaccount_window(object):
    def setupUi(self, deleteaccount_window):
        deleteaccount_window.setObjectName("deleteaccount_window")
        deleteaccount_window.resize(473, 351)
        deleteaccount_window.setMinimumSize(QtCore.QSize(473, 351))
        deleteaccount_window.setMaximumSize(QtCore.QSize(473, 351))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        deleteaccount_window.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/main.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        deleteaccount_window.setWindowIcon(icon)
        self.accountname_label = QtWidgets.QLabel(deleteaccount_window)
        self.accountname_label.setGeometry(QtCore.QRect(30, 80, 131, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.accountname_label.setFont(font)
        self.accountname_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.accountname_label.setObjectName("accountname_label")
        self.username_label = QtWidgets.QLabel(deleteaccount_window)
        self.username_label.setGeometry(QtCore.QRect(30, 170, 121, 31))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.username_label.setFont(font)
        self.username_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.username_label.setObjectName("username_label")
        self.accountname_lineedit = QtWidgets.QLineEdit(deleteaccount_window)
        self.accountname_lineedit.setGeometry(QtCore.QRect(200, 80, 221, 31))
        self.accountname_lineedit.setObjectName("accountname_lineedit")
        self.username_lineedit = QtWidgets.QLineEdit(deleteaccount_window)
        self.username_lineedit.setGeometry(QtCore.QRect(200, 170, 221, 31))
        self.username_lineedit.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.username_lineedit.setObjectName("username_lineedit")
        self.cancel_button = QtWidgets.QPushButton(deleteaccount_window)
        self.cancel_button.setGeometry(QtCore.QRect(144, 270, 91, 26))
        self.cancel_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_button.setToolTip("")
        self.cancel_button.setDefault(True)
        self.cancel_button.setObjectName("cancel_button")
        self.ok_button = QtWidgets.QPushButton(deleteaccount_window)
        self.ok_button.setGeometry(QtCore.QRect(250, 270, 91, 26))
        self.ok_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.ok_button.setAutoDefault(True)
        self.ok_button.setDefault(True)
        self.ok_button.setObjectName("ok_button")

        self.retranslateUi(deleteaccount_window)
        QtCore.QMetaObject.connectSlotsByName(deleteaccount_window)

    def retranslateUi(self, deleteaccount_window):
        _translate = QtCore.QCoreApplication.translate
        deleteaccount_window.setWindowTitle(_translate("deleteaccount_window", "Password Protector"))
        self.accountname_label.setText(_translate("deleteaccount_window", "Account Name*"))
        self.username_label.setText(_translate("deleteaccount_window", "User Name*"))
        self.accountname_lineedit.setPlaceholderText(_translate("deleteaccount_window", "e. g. Facebook"))
        self.username_lineedit.setPlaceholderText(_translate("deleteaccount_window", "User Name"))
        self.cancel_button.setText(_translate("deleteaccount_window", "Cancel"))
        self.ok_button.setText(_translate("deleteaccount_window", "Ok"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    deleteaccount_window = QtWidgets.QWidget()
    ui = Ui_deleteaccount_window()
    ui.setupUi(deleteaccount_window)
    deleteaccount_window.show()
    sys.exit(app.exec_())
