from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_deleteuser_window(object):
    def setupUi(self, deleteuser_window):
        deleteuser_window.setObjectName("deleteuser_window")
        deleteuser_window.resize(429, 300)
        deleteuser_window.setMinimumSize(QtCore.QSize(429, 300))
        deleteuser_window.setMaximumSize(QtCore.QSize(429, 300))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(10)
        deleteuser_window.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("resources/main.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        deleteuser_window.setWindowIcon(icon)
        self.username_label = QtWidgets.QLabel(deleteuser_window)
        self.username_label.setGeometry(QtCore.QRect(70, 80, 71, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.username_label.setFont(font)
        self.username_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(deleteuser_window)
        self.password_label.setGeometry(QtCore.QRect(60, 140, 81, 16))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.password_label.setFont(font)
        self.password_label.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.password_label.setObjectName("password_label")
        self.username_lineedit = QtWidgets.QLineEdit(deleteuser_window)
        self.username_lineedit.setGeometry(QtCore.QRect(170, 90, 191, 20))
        self.username_lineedit.setObjectName("username_lineedit")
        self.password_lineedit = QtWidgets.QLineEdit(deleteuser_window)
        self.password_lineedit.setGeometry(QtCore.QRect(170, 140, 191, 20))
        self.password_lineedit.setEchoMode(QtWidgets.QLineEdit.Password)
        self.password_lineedit.setObjectName("password_lineedit")
        self.delete_button = QtWidgets.QPushButton(deleteuser_window)
        self.delete_button.setGeometry(QtCore.QRect(280, 220, 85, 26))
        self.delete_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.delete_button.setDefault(True)
        self.delete_button.setObjectName("delete_button")
        self.cancel_button = QtWidgets.QPushButton(deleteuser_window)
        self.cancel_button.setGeometry(QtCore.QRect(110, 220, 85, 26))
        self.cancel_button.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.cancel_button.setDefault(True)
        self.cancel_button.setObjectName("cancel_button")

        self.retranslateUi(deleteuser_window)
        QtCore.QMetaObject.connectSlotsByName(deleteuser_window)

    def retranslateUi(self, deleteuser_window):
        _translate = QtCore.QCoreApplication.translate
        deleteuser_window.setWindowTitle(_translate("deleteuser_window", "Password Protector"))
        self.username_label.setText(_translate("deleteuser_window", "Name"))
        self.password_label.setText(_translate("deleteuser_window", "Password"))
        self.username_lineedit.setPlaceholderText(_translate("deleteuser_window", "Enter Username"))
        self.password_lineedit.setPlaceholderText(_translate("deleteuser_window", "Password"))
        self.delete_button.setText(_translate("deleteuser_window", "Delete"))
        self.cancel_button.setText(_translate("deleteuser_window", "Cancel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    deleteuser_window = QtWidgets.QWidget()
    ui = Ui_deleteuser_window()
    ui.setupUi(deleteuser_window)
    deleteuser_window.show()
    sys.exit(app.exec_())
